CREATE DATABASE IF NOT EXISTS food_delivery;
USE food_delivery;
CREATE TABLE IF NOT EXISTS menu(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100) NOT NULL,price DECIMAL(10,2) NOT NULL,category VARCHAR(50) NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id INT PRIMARY KEY AUTO_INCREMENT,customer_name VARCHAR(100) NOT NULL,items TEXT NOT NULL,total_amount DECIMAL(10,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO menu(name,price,category) VALUES ('Veg Burger',129.00,'Burgers'),('Paneer Wrap',159.00,'Wraps'),('Masala Pizza',249.00,'Pizza');